// Configuration data that matches Duda's structure
export const data = {
  config: {
    dark_mode: false,
    view_all_cancellations_link: { href: "https://www.google.com" },
    hide_widget_title: false,
    api_token: "ZHVkYTpGNTNgLVs5Q1AiclFTcD1ooo",
    api_url: "https://api.cancelledmatches.com/v1/matches",
  },
  collections: ["my_collection"],
  device: "desktop",
  inEditor: true,
};

// Mock collection data
export const collectionData = {
  my_collection: [
    {
      uuid: "84b71948a810447b9e5024ea651b3229",
      data: {
        date: "2026-01-15T00:00:00Z",
        all_matches_cancelled: true,
        matches: [
          {
            id: "b0dc7b72-5047-4f9a-a0c4-9e0f2364d0dc",
            home_team_name: "Team X",
            opponent_team_name: "Team Y",
            opponent_club_name: null,
            time: "23:23",
            location: "Sportp. 'Small Brandt'",
            field: "Field 1",
            home_team_label: "Onder 12",
            home_team_parent_label: "Junioren",
            away_team_label: null,
            away_team_parent_label: null,
            away_team_gender: null,
            gender: "male",
            home_team_gender: "male",
            cancellation_reason: "Field unavailable due to rain",
            is_home_match: true,
            category: "Junioren",
            category_code: "3778",
            sub_category: "Jongens O12",
          },
          {
            id: "a1ed8c83-6158-5g0b-b1d5-0f1g3475e1ed",
            home_team_name: "Team Z",
            opponent_team_name: "MO14-5",
            opponent_club_name: "FC Amsterdam",
            time: "10:30",
            location: "Sportp. 'Small Brandt'",
            field: "Field 2",
            home_team_label: "Onder 14",
            home_team_parent_label: "Junioren",
            away_team_label: "Onder 14",
            away_team_parent_label: "Junioren",
            away_team_gender: "female",
            gender: "female",
            home_team_gender: "female",
            cancellation_reason: "Weather conditions",
            is_home_match: true,
            category: "Junioren",
            category_code: "3779",
            sub_category: "Meisjes O14",
          },
          {
            id: "a1ed8c83-6158-5g0b-b1d5-0f1g3475e1ed2",
            home_team_name: "Team Z",
            opponent_team_name: "Team A",
            opponent_club_name: "FC Amsterdam",
            time: "10:30",
            location: "Sportp. 'Small Brandt'",
            field: "Field 3",
            home_team_label: "Onder 14",
            home_team_parent_label: "Junioren",
            away_team_label: "Team B",
            away_team_parent_label: "Junioren",
            away_team_gender: "female",
            gender: "female",
            home_team_gender: "female",
            cancellation_reason: "Field unavailable due to rain",
            is_home_match: true,
            category: "Junioren",
            category_code: "3779",
            sub_category: "Meisjes O14",
          },
          {
            id: "a1ed8c83-6158-5g0b-b1d5-0f1g3475e1ed3",
            home_team_name: "Team Z",
            opponent_team_name: "Team A",
            opponent_club_name: "FC Amsterdam",
            time: "10:30",
            location: "Sportp. 'Small Brandt'",
            field: "Field 3",
            home_team_label: "Onder 14",
            home_team_parent_label: "Junioren",
            away_team_label: "Team B",
            away_team_parent_label: "Junioren",
            away_team_gender: "female",
            gender: "female",
            home_team_gender: "female",
            cancellation_reason: "Field unavailable due to rain",
            is_home_match: true,
            category: "Junioren",
            category_code: "3779",
            sub_category: "Meisjes O14",
          },
        ],
        matches_count: 3,
      },
      correlationId: "2026-01-15T00:00:00Z",
      page_item_url: "2026-01-15T00:00:00Z",
    },
    {
      uuid: "95c82059b921558caf6135fb762c4330",
      data: {
        date: "2026-01-16T00:00:00Z",
        all_matches_cancelled: false,
        matches: [
          {
            id: "c2fe9d94-7159-6h1c-c2e6-1g2h4586f2fe",
            home_team_name: "Team Alpha",
            opponent_team_name: "Team Beta",
            opponent_club_name: "HC Rotterdam",
            time: "14:00",
            location: "Sportpark De Vliet",
            field: "Field A",
            home_team_label: "Onder 16",
            home_team_parent_label: "Junioren",
            away_team_label: "Onder 16",
            away_team_parent_label: "Junioren",
            away_team_gender: "male",
            gender: "male",
            home_team_gender: "male",
            cancellation_reason: "Insufficient players",
            is_home_match: true,
            category: "Junioren",
            category_code: "3780",
            sub_category: "Jongens O16",
          },
          {
            id: "d3gf0ea5-8260-7i2d-d3f7-2h3i5697g3gf",
            home_team_name: "Team Gamma",
            opponent_team_name: "VO18-3",
            opponent_club_name: "SV Den Haag",
            time: "16:30",
            location: "Sportpark De Vliet",
            field: "Field B",
            home_team_label: "Onder 18",
            home_team_parent_label: "Junioren",
            away_team_label: "Onder 18",
            away_team_parent_label: "Junioren",
            away_team_gender: "female",
            gender: "female",
            home_team_gender: "female",
            cancellation_reason: "Opponent team withdrew",
            is_home_match: false,
            category: "Junioren",
            category_code: "3781",
            sub_category: "Meisjes O18",
          },
        ],
        matches_count: 2,
      },
      correlationId: "2026-01-16T00:00:00Z",
      page_item_url: "2026-01-16T00:00:00Z",
    },
    {
      uuid: "a6d9316ac032669dbg7246gc873d5441",
      data: {
        date: "2026-01-17T00:00:00Z",
        all_matches_cancelled: true,
        matches: [
          {
            id: "e4hg1fb6-9371-8j3e-e4g8-3i4j6708h4hg",
            home_team_name: "Team Delta",
            opponent_team_name: "Team Epsilon",
            opponent_club_name: null,
            time: "09:00",
            location: "Sportcomplex Noord",
            field: "Field 3",
            home_team_label: "Onder 10",
            home_team_parent_label: "Junioren",
            away_team_label: null,
            away_team_parent_label: null,
            away_team_gender: null,
            gender: "male",
            home_team_gender: "male",
            cancellation_reason: "Severe weather warning",
            is_home_match: true,
            category: "Junioren",
            category_code: "3782",
            sub_category: "Jongens O10",
          },
          {
            id: "f5ih2gc7-a482-9k4f-f5h9-4j5k7819i5ih",
            home_team_name: "Team Zeta",
            opponent_team_name: "VO12-2",
            opponent_club_name: "HC Utrecht",
            time: "11:15",
            location: "Sportcomplex Noord",
            field: "Field 4",
            home_team_label: "Onder 12",
            home_team_parent_label: "Junioren",
            away_team_label: "Onder 12",
            away_team_parent_label: "Junioren",
            away_team_gender: "female",
            gender: "female",
            home_team_gender: "female",
            cancellation_reason: "Severe weather warning",
            is_home_match: true,
            category: "Junioren",
            category_code: "3783",
            sub_category: "Meisjes O12",
          },
          {
            id: "g6ji3hd8-b593-0l5g-g6i0-5k6l8920j6ji",
            home_team_name: "Team Eta",
            opponent_team_name: "MO16-4",
            opponent_club_name: "AH&BC Amsterdam",
            time: "13:45",
            location: "Sportcomplex Noord",
            field: "Field 5",
            home_team_label: "Onder 16",
            home_team_parent_label: "Junioren",
            away_team_label: "Onder 16",
            away_team_parent_label: "Junioren",
            away_team_gender: "male",
            gender: "male",
            home_team_gender: "male",
            cancellation_reason: "Severe weather warning",
            is_home_match: false,
            category: "Junioren",
            category_code: "3784",
            sub_category: "Jongens O16",
          },
        ],
        matches_count: 3,
      },
      correlationId: "2026-01-17T00:00:00Z",
      page_item_url: "2026-01-17T00:00:00Z",
    },
    {
      uuid: "b7e0427bd143770ec1h8357hd984e6552",
      data: {
        date: "2026-01-18T00:00:00Z",
        all_matches_cancelled: false,
        matches: [
          {
            id: "h7kj4ie9-c604-1m6h-h7j1-6l7m9031k7kj",
            home_team_name: "Team Theta",
            opponent_team_name: "Team Iota",
            opponent_club_name: "HC Bloemendaal",
            time: "15:20",
            location: "Stadion De Hout",
            field: "Main Field",
            home_team_label: "Onder 20",
            home_team_parent_label: "Senioren",
            away_team_label: "Onder 20",
            away_team_parent_label: "Senioren",
            away_team_gender: "male",
            gender: "male",
            home_team_gender: "male",
            cancellation_reason: "Field maintenance",
            is_home_match: true,
            category: "Senioren",
            category_code: "4785",
            sub_category: "Heren O20",
          },
        ],
        matches_count: 1,
      },
      correlationId: "2026-01-18T00:00:00Z",
      page_item_url: "2026-01-18T00:00:00Z",
    },
    {
      uuid: "c8f1538ce254881fd2i9468ie095f7663",
      data: {
        date: "2026-01-19T00:00:00Z",
        all_matches_cancelled: false,
        matches: [
          {
            id: "i8lk5jf0-d715-2n7i-i8k2-7m8n0142l8lk",
            home_team_name: "Team Kappa",
            opponent_team_name: "VO14-1",
            opponent_club_name: "SCHC",
            time: "10:00",
            location: "Sportpark De Krommerijn",
            field: "Field 1",
            home_team_label: "Onder 14",
            home_team_parent_label: "Junioren",
            away_team_label: "Onder 14",
            away_team_parent_label: "Junioren",
            away_team_gender: "female",
            gender: "female",
            home_team_gender: "female",
            cancellation_reason: "Referee unavailable",
            is_home_match: true,
            category: "Junioren",
            category_code: "3786",
            sub_category: "Meisjes O14",
          },
          {
            id: "j9ml6kg1-e826-3o8j-j9l3-8n9o1253m9ml",
            home_team_name: "Team Lambda",
            opponent_team_name: "MO12-6",
            opponent_club_name: "HC 's-Hertogenbosch",
            time: "12:30",
            location: "Sportpark De Krommerijn",
            field: "Field 2",
            home_team_label: "Onder 12",
            home_team_parent_label: "Junioren",
            away_team_label: "Onder 12",
            away_team_parent_label: "Junioren",
            away_team_gender: "male",
            gender: "male",
            home_team_gender: "male",
            cancellation_reason: "Referee unavailable",
            is_home_match: false,
            category: "Junioren",
            category_code: "3787",
            sub_category: "Jongens O12",
          },
        ],
        matches_count: 2,
      },
      correlationId: "2026-01-19T00:00:00Z",
      page_item_url: "2026-01-19T00:00:00Z",
    },
    {
      uuid: "d9g2649df365992ge3j0579jf106g8774",
      data: {
        date: "2026-01-20T00:00:00Z",
        all_matches_cancelled: true,
        matches: [
          {
            id: "k0nm7lh2-f937-4p9k-k0m4-9o0p2364n0nm",
            home_team_name: "Team Mu",
            opponent_team_name: "Team Nu",
            opponent_club_name: null,
            time: "08:30",
            location: "Sportpark Zuid",
            field: "Field A",
            home_team_label: "Onder 8",
            home_team_parent_label: "Junioren",
            away_team_label: null,
            away_team_parent_label: null,
            away_team_gender: null,
            gender: "male",
            home_team_gender: "male",
            cancellation_reason: "Frozen pitch",
            is_home_match: true,
            category: "Junioren",
            category_code: "3788",
            sub_category: "Jongens O8",
          },
          {
            id: "l1on8mi3-g048-5q0l-l1n5-0p1q3475o1on",
            home_team_name: "Team Xi",
            opponent_team_name: "VO10-3",
            opponent_club_name: "HC Oranje-Rood",
            time: "10:45",
            location: "Sportpark Zuid",
            field: "Field B",
            home_team_label: "Onder 10",
            home_team_parent_label: "Junioren",
            away_team_label: "Onder 10",
            away_team_parent_label: "Junioren",
            away_team_gender: "female",
            gender: "female",
            home_team_gender: "female",
            cancellation_reason: "Frozen pitch",
            is_home_match: true,
            category: "Junioren",
            category_code: "3789",
            sub_category: "Meisjes O10",
          },
        ],
        matches_count: 2,
      },
      correlationId: "2026-01-20T00:00:00Z",
      page_item_url: "2026-01-20T00:00:00Z",
    },
  ],
};

// Mock API functions
export const api = {
  collections: {
    getCollection: ({ collectionName }) => {
      return Promise.resolve(collectionData[collectionName] || []);
    },
  },
};
