export const data = {
  config: {
    faqs_list: [
      {
        category_title: "Competitions & Events",
        assets: [
          {
            url: "https://images.knltb.club/api/gallery/1491/16/_/02ca6ab1-f920-47f9-b9fe-5e5a9077bba2.png",
            caption: "placeholder_doek.png",
            type: "image",
            mimetype: "image/png",
          },
          {
            url: "https://images.knltb.club/api/gallery/1491/16/_/6997989c-7019-4673-adcb-3d554f28ecba.jpg",
            caption: "Duel 2.jpg",
            type: "image",
            mimetype: "image/jpeg",
          },
          {
            url: "https://images.knltb.club/api/gallery/1491/16/_/345fe8dd-5c3b-4518-9aaa-1ef63011efbc.jpg",
            caption: "Ball and Stick 1.jpg",
            type: "image",
            mimetype: "image/jpeg",
          },
          {
            url: "https://storage.knltb.club/clubid-1491/Medialibrary/6862085a-48d5-4b3a-b15a-ae17ae41a2bc.docx",
            caption: "Test Word.docx",
            type: "document",
            mimetype:
              "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          },
          {
            url: "https://storage.knltb.club/clubid-1491/Medialibrary/336b3d07-6d7b-4371-bf33-b37d8a8fab92.xlsx",
            caption: "Test Excel.xlsx",
            type: "document",
            mimetype:
              "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
          },
          {
            url: "https://storage.knltb.club/clubid-1491/Medialibrary/a222589d-1352-4c31-85b2-291d1bb152cc.pdf",
            caption: "Test pdf.pdf",
            type: "document",
            mimetype: "application/pdf",
          },
        ],
        category_id: 698,
        updated_at: "2025-03-12T19:38:16Z",
        author: "John Doe",
        intro: null,
        description:
          "<p><strong>Line Coordinator<br></strong>The line coordinator is the primary contact point for the players, parents, coaches, and trainers of all teams within the relevant youth line.</p>",
        created_at: "2024-12-19T03:10:47Z",
        category_subtitle: null,
        id: "2001",
        title: "Contributing Financial Support?",
      },
      {
        category_title: "Competitions & Events",
        assets: [
          {
            url: "https://images.knltb.club/api/gallery/1491/16/_/02ca6ab1-f920-47f9-b9fe-5e5a9077bba2.png",
            caption: "placeholder_doek.png",
            type: "image",
            mimetype: "image/png",
          },
        ],
        category_id: 698,
        updated_at: "2025-02-17T14:09:41Z",
        author: null,
        intro: null,
        description:
          "<p><strong>Members Information System Almeerse</strong><br>The online system where all information for/from the members is managed.&nbsp;</p>",
        created_at: "2024-12-19T03:10:47Z",
        category_subtitle: null,
        id: "2004",
        title: "When are competitions and events announced?",
      },
      {
        category_title: "Competitions & Events",
        assets: [
          {
            url: "https://images.knltb.club/api/gallery/1491/16/_/1915f1a7-d7f6-4e5b-91ae-f8937933cc4a.jpg",
            caption: "Ball and Stick 1.jpg",
            type: "image",
            mimetype: "image/jpeg",
          },
        ],
        category_id: 698,
        updated_at: "2025-02-17T14:10:17Z",
        author: null,
        intro: null,
        description:
          "<p>At the end of the hockey season, CEESARS are awarded for, among others, best team, player, coach, and goalkeeper of the year. The trophy is named after the founder of the club: Cees van Baar.</p>",
        created_at: "2024-12-19T03:10:47Z",
        category_subtitle: null,
        id: "2011",
        title: "What is the CEESARS program?",
      },
      {
        category_title: "Competitions & Events",
        assets: [],
        category_id: 698,
        updated_at: "2025-02-17T14:10:52Z",
        author: null,
        intro: null,
        description:
          "<p><strong>Bar Administration System</strong><br>System that allows members to schedule themselves in the bar roster.</p>",
        created_at: "2024-12-19T03:10:47Z",
        category_subtitle: null,
        id: "2014",
        title: "What is the Bar Administration System?",
      },
      {
        category_title: "Competitions & Events",
        assets: [],
        category_id: 698,
        updated_at: "2025-02-17T14:11:07Z",
        author: null,
        intro: null,
        description:
          "<p><strong>Members Arbitration System</strong><br>Allows referees to schedule the matches they will officiate themselves.</p>",
        created_at: "2024-12-19T03:10:47Z",
        category_subtitle: null,
        id: "2015",
        title: "What is LARS?",
      },
      {
        category_title: "Competitions & Events",
        assets: [],
        category_id: 698,
        updated_at: null,
        author: "Sabine van Stek",
        intro: null,
        description:
          "<p><strong>Daily Management Team</strong><br>Responsible for the daily operations of the club.</p>",
        created_at: "2025-02-17T14:12:17Z",
        category_subtitle: null,
        id: "2708",
        title: "What is DMT?",
      },
      {
        category_title: "Facilities & Equipment",
        assets: [],
        category_id: 992,
        updated_at: "2025-02-17T13:02:06Z",
        author: null,
        intro: null,
        description:
          '<p><a href="://www.almeersehockeyclub.nl/contactgegevens-en-plattegrond" target="_blank" rel="noopener noreferrer">Click here for the map of our facility</a><br><br></p>',
        created_at: "2024-12-19T03:10:47Z",
        category_subtitle: null,
        id: "2003",
        title: "Where can I find the map?",
      },
    ],
    dark_mode: true,
    default_desktop_view: "cards",
    default_mobile_view: "list",
    hide_search_bar: false,
    hide_created_at: false,
    hide_updated_at: false,
    hide_author: false,
    collapse_categories: true,
  },
  device: "desktop",
};
