// Main configuration
export const data = {
  collections: ["Toekomstige_wedstrijden"],
  config: {
    showRef: true,
  },
};

// Mock API response for getCollection
export const mockCollectionData = {
  Toekomstige_wedstrijden: [
    {
      data: {
        collectionname: "matches_jan_2026",
        date: "2026-01-18T00:00Z",
        matches_count: 3,
        title: "18-01-2026",
        page_item_url: "2026-01-18T00:00Z",
        uuid: "a27cac85fa34d0182133d6b257afd1",
      },
    },
    {
      data: {
        collectionname: "matches_jan_2026",
        date: "2026-01-25T00:00Z",
        matches_count: 2,
        title: "25-01-2026",
        page_item_url: "2026-01-25T00:00Z",
        uuid: "a27cac85fa34d0182133d6b257afd2",
      },
    },
    {
      data: {
        collectionname: "matches_feb_2026",
        date: "2026-02-08T00:00Z",
        matches_count: 4,
        title: "08-02-2026",
        page_item_url: "2026-02-08T00:00Z",
        uuid: "a27cac85fa34d0182133d6b257afd3",
      },
    },
    {
      data: {
        collectionname: "matches_feb_2026",
        date: "2026-02-22T00:00Z",
        matches_count: 3,
        title: "22-02-2026",
        page_item_url: "2026-02-22T00:00Z",
        uuid: "a27cac85fa34d0182133d6b257afd4",
      },
    },
    {
      data: {
        collectionname: "matches_mar_2026",
        date: "2026-03-15T00:00Z",
        matches_count: 4,
        title: "15-03-2026",
        page_item_url: "2026-03-15T00:00Z",
        uuid: "a27cac85fa34d0182133d6b257afd5",
      },
    },
    {
      data: {
        collectionname: "matches_apr_2026",
        date: "2026-04-12T00:00Z",
        matches_count: 3,
        title: "12-04-2026",
        page_item_url: "2026-04-12T00:00Z",
        uuid: "a27cac85fa34d0182133d6b257afd6",
      },
    },
    {
      data: {
        collectionname: "matches_may_2026",
        date: "2026-05-10T00:00Z",
        matches_count: 2,
        title: "10-05-2026",
        page_item_url: "2026-05-10T00:00Z",
        uuid: "a27cac85fa34d0182133d6b257afd7",
      },
    },
  ],
  matches_jan_2026: [
    {
      data: {
        arrival_time: "08:30",
        away_team_club_logo_url: "assets/logos/logo-1.jpg",
        away_team_club_name: "HC Rotterdam",
        away_team_is_current: false,
        away_team_name: "JD1",
        category: "Juniors",
        category_code: "JD1",
        club_remarks: "Important match - preparation for finals",
        code: "12345",
        date: "18-01-2026",
        extra_remarks: null,
        field: "Field 1",
        gender: "male",
        home_team_club_logo_url: "assets/logos/logo-4.jpg",
        home_team_club_name: "Almeerse HC",
        home_team_is_current: true,
        home_team_name: "JD1",
        id: "match-jan-1",
        is_cancelled: false,
        is_home_match: true,
        is_selected_team: true,
        location: {
          address: {
            street: "Tuinkruidepad",
            house_number: "4",
            house_number_extension: null,
            zip_code: "1312JN",
            city: "Almere",
          },
          location_quarters: null,
          name: "Sportpark Klein Brandt",
          phones: ["(+31) 36 555 0101"],
          web_pages: ["www.sportpark-klein-brandt.nl"],
        },
        time: "09:30",
      },
    },
    {
      data: {
        arrival_time: "13:00",
        away_team_club_logo_url: "assets/logos/logo-2.jpg",
        away_team_club_name: "HC Utrecht",
        away_team_is_current: false,
        away_team_name: "MD1",
        category: "Juniors",
        category_code: "MD1",
        club_remarks: "Regular league match",
        code: "12346",
        date: "18-01-2026",
        extra_remarks: null,
        field: "Field 2",
        gender: "female",
        home_team_club_logo_url: "assets/logos/logo-4.jpg",
        home_team_club_name: "Almeerse HC",
        home_team_is_current: true,
        home_team_name: "MD1",
        id: "match-jan-2",
        is_cancelled: false,
        is_home_match: true,
        is_selected_team: true,
        location: {
          address: {
            street: "Tuinkruidepad",
            house_number: "4",
            house_number_extension: null,
            zip_code: "1312JN",
            city: "Almere",
          },
          location_quarters: null,
          name: "Sportpark Klein Brandt",
          phones: ["(+31) 36 555 0102"],
          web_pages: ["www.sportpark-klein-brandt.nl"],
        },
        time: "14:00",
      },
    },
    {
      data: {
        arrival_time: "16:00",
        away_team_club_logo_url: "assets/logos/logo-3.avif",
        away_team_club_name: "HC Arnhem",
        away_team_is_current: false,
        away_team_name: "AD2",
        category: "Adults",
        category_code: "AD2",
        club_remarks: null,
        code: "12347",
        date: "18-01-2026",
        extra_remarks: "Match moved from Sunday",
        field: "Field 3",
        gender: "male",
        home_team_club_logo_url: "assets/logos/logo-4.jpg",
        home_team_club_name: "Almeerse HC",
        home_team_is_current: true,
        home_team_name: "AD2",
        id: "match-jan-3",
        is_cancelled: false,
        is_home_match: false,
        is_selected_team: false,
        location: {
          address: {
            street: "Sportlaan",
            house_number: "50",
            house_number_extension: null,
            zip_code: "6800AB",
            city: "Arnhem",
          },
          location_quarters: null,
          name: "Sportpark Arnhem",
          phones: ["(+31) 26 555 0103"],
          web_pages: ["www.sportpark-arnhem.nl"],
        },
        time: "16:30",
      },
    },
  ],
  matches_feb_2026: [
    {
      data: {
        arrival_time: "09:00",
        away_team_club_logo_url: "assets/logos/logo-4.jpg",
        away_team_club_name: "HC Groningen",
        away_team_is_current: false,
        away_team_name: "JD2",
        category: "Juniors",
        category_code: "JD2",
        club_remarks: "Regional championship qualifier",
        code: "12348",
        date: "08-02-2026",
        extra_remarks: null,
        field: "Field A",
        gender: "male",
        home_team_club_logo_url: "assets/logos/logo-4.jpg",
        home_team_club_name: "Almeerse HC",
        home_team_is_current: true,
        home_team_name: "JD2",
        id: "match-feb-1",
        is_cancelled: false,
        is_home_match: true,
        is_selected_team: true,
        location: {
          address: {
            street: "Tuinkruidepad",
            house_number: "4",
            house_number_extension: null,
            zip_code: "1312JN",
            city: "Almere",
          },
          location_quarters: null,
          name: "Sportpark Klein Brandt",
          phones: ["(+31) 36 555 0104"],
          web_pages: ["www.sportpark-klein-brandt.nl"],
        },
        time: "10:00",
      },
    },
    {
      data: {
        arrival_time: "12:00",
        away_team_club_logo_url: "assets/logos/logo-1.jpg",
        away_team_club_name: "HC Leiden",
        away_team_is_current: false,
        away_team_name: "MD2",
        category: "Juniors",
        category_code: "MD2",
        club_remarks: null,
        code: "12349",
        date: "08-02-2026",
        extra_remarks: null,
        field: "Field B",
        gender: "female",
        home_team_club_logo_url: "assets/logos/logo-4.jpg",
        home_team_club_name: "Almeerse HC",
        home_team_is_current: true,
        home_team_name: "MD2",
        id: "match-feb-2",
        is_cancelled: false,
        is_home_match: true,
        is_selected_team: true,
        location: {
          address: {
            street: "Tuinkruidepad",
            house_number: "4",
            house_number_extension: null,
            zip_code: "1312JN",
            city: "Almere",
          },
          location_quarters: null,
          name: "Sportpark Klein Brandt",
          phones: ["(+31) 36 555 0105"],
          web_pages: ["www.sportpark-klein-brandt.nl"],
        },
        time: "13:30",
      },
    },
    {
      data: {
        arrival_time: "11:00",
        away_team_club_logo_url: "assets/logos/logo-2.jpg",
        away_team_club_name: "HC Amsterdam",
        away_team_is_current: false,
        away_team_name: "AD1",
        category: "Adults",
        category_code: "AD1",
        club_remarks: "Top league match",
        code: "12350",
        date: "22-02-2026",
        extra_remarks: null,
        field: "Field 1",
        gender: "male",
        home_team_club_logo_url: "assets/logos/logo-4.jpg",
        home_team_club_name: "Almeerse HC",
        home_team_is_current: true,
        home_team_name: "AD1",
        id: "match-feb-3",
        is_cancelled: false,
        is_home_match: false,
        is_selected_team: false,
        location: {
          address: {
            street: "Amsterdam Boulevard",
            house_number: "100",
            house_number_extension: null,
            zip_code: "1018AB",
            city: "Amsterdam",
          },
          location_quarters: null,
          name: "Hardenbergplein Sports Center",
          phones: ["(+31) 20 555 0106"],
          web_pages: ["www.hardenbergplein-sports.nl"],
        },
        time: "12:00",
      },
    },
    {
      data: {
        arrival_time: null,
        away_team_club_logo_url: null,
        away_team_club_name: null,
        away_team_is_current: false,
        away_team_name: "Substitutes match",
        category: null,
        category_code: null,
        club_remarks: "Training and substitutes only",
        code: null,
        date: "22-02-2026",
        extra_remarks: null,
        field: "Field 2",
        gender: null,
        home_team_club_logo_url: "assets/logos/logo-4.jpg",
        home_team_club_name: "Almeerse HC",
        home_team_is_current: true,
        home_team_name: "Training Group A",
        id: "match-feb-4",
        is_cancelled: false,
        is_home_match: true,
        is_selected_team: false,
        location: {
          address: {
            street: "Tuinkruidepad",
            house_number: "4",
            house_number_extension: null,
            zip_code: "1312JN",
            city: "Almere",
          },
          location_quarters: null,
          name: "Sportpark Klein Brandt",
          phones: ["(+31) 36 555 0107"],
          web_pages: ["www.sportpark-klein-brandt.nl"],
        },
        time: "15:00",
      },
    },
  ],
  matches_mar_2026: [
    {
      data: {
        arrival_time: "08:45",
        away_team_club_logo_url: "assets/logos/logo-3.avif",
        away_team_club_name: "HC Tilburg",
        away_team_is_current: false,
        away_team_name: "JD1",
        category: "Juniors",
        category_code: "JD1",
        club_remarks: "District championship round",
        code: "12351",
        date: "15-03-2026",
        extra_remarks: null,
        field: "Field 1",
        gender: "male",
        home_team_club_logo_url: "assets/logos/logo-4.jpg",
        home_team_club_name: "Almeerse HC",
        home_team_is_current: true,
        home_team_name: "JD1",
        id: "match-mar-1",
        is_cancelled: false,
        is_home_match: true,
        is_selected_team: true,
        location: {
          address: {
            street: "Tuinkruidepad",
            house_number: "4",
            house_number_extension: null,
            zip_code: "1312JN",
            city: "Almere",
          },
          location_quarters: null,
          name: "Sportpark Klein Brandt",
          phones: ["(+31) 36 555 0108"],
          web_pages: ["www.sportpark-klein-brandt.nl"],
        },
        time: "09:30",
      },
    },
    {
      data: {
        arrival_time: "12:30",
        away_team_club_logo_url: "assets/logos/logo-4.jpg",
        away_team_club_name: "HC Den Haag",
        away_team_is_current: false,
        away_team_name: "MD1",
        category: "Juniors",
        category_code: "MD1",
        club_remarks: null,
        code: "12352",
        date: "15-03-2026",
        extra_remarks: null,
        field: "Field 2",
        gender: "female",
        home_team_club_logo_url: "assets/logos/logo-4.jpg",
        home_team_club_name: "Almeerse HC",
        home_team_is_current: true,
        home_team_name: "MD1",
        id: "match-mar-2",
        is_cancelled: false,
        is_home_match: true,
        is_selected_team: true,
        location: {
          address: {
            street: "Tuinkruidepad",
            house_number: "4",
            house_number_extension: null,
            zip_code: "1312JN",
            city: "Almere",
          },
          location_quarters: null,
          name: "Sportpark Klein Brandt",
          phones: ["(+31) 36 555 0109"],
          web_pages: ["www.sportpark-klein-brandt.nl"],
        },
        time: "14:00",
      },
    },
    {
      data: {
        arrival_time: "10:00",
        away_team_club_logo_url: "assets/logos/logo-1.jpg",
        away_team_club_name: "HC Eindhoven",
        away_team_is_current: false,
        away_team_name: "AD1",
        category: "Adults",
        category_code: "AD1",
        club_remarks: "Mid-season form check",
        code: "12353",
        date: "15-03-2026",
        extra_remarks: null,
        field: "Field A",
        gender: "male",
        home_team_club_logo_url: "assets/logos/logo-4.jpg",
        home_team_club_name: "Almeerse HC",
        home_team_is_current: true,
        home_team_name: "AD1",
        id: "match-mar-3",
        is_cancelled: false,
        is_home_match: false,
        is_selected_team: false,
        location: {
          address: {
            street: "Stadionplein",
            house_number: "25",
            house_number_extension: null,
            zip_code: "5600AB",
            city: "Eindhoven",
          },
          location_quarters: null,
          name: "PSV Sports Park",
          phones: ["(+31) 40 555 0110"],
          web_pages: ["www.psv-sports.nl"],
        },
        time: "11:00",
      },
    },
    {
      data: {
        arrival_time: "14:00",
        away_team_club_logo_url: "assets/logos/logo-2.jpg",
        away_team_club_name: "HC Apeldoorn",
        away_team_is_current: false,
        away_team_name: "Senior Mixed",
        category: "Adults",
        category_code: "MX",
        club_remarks: "Friendly match",
        code: "12354",
        date: "15-03-2026",
        extra_remarks: null,
        field: "Field 3",
        gender: null,
        home_team_club_logo_url: "assets/logos/logo-4.jpg",
        home_team_club_name: "Almeerse HC",
        home_team_is_current: true,
        home_team_name: "Senior Mixed",
        id: "match-mar-4",
        is_cancelled: false,
        is_home_match: true,
        is_selected_team: false,
        location: {
          address: {
            street: "Tuinkruidepad",
            house_number: "4",
            house_number_extension: null,
            zip_code: "1312JN",
            city: "Almere",
          },
          location_quarters: null,
          name: "Sportpark Klein Brandt",
          phones: ["(+31) 36 555 0111"],
          web_pages: ["www.sportpark-klein-brandt.nl"],
        },
        time: "15:00",
      },
    },
  ],
  matches_apr_2026: [
    {
      data: {
        arrival_time: "09:00",
        away_team_club_logo_url: "assets/logos/logo-3.avif",
        away_team_club_name: "HC Zwolle",
        away_team_is_current: false,
        away_team_name: "JD1",
        category: "Juniors",
        category_code: "JD1",
        club_remarks: "Spring league match",
        code: "12355",
        date: "12-04-2026",
        extra_remarks: null,
        field: "Field 1",
        gender: "male",
        home_team_club_logo_url: "assets/logos/logo-4.jpg",
        home_team_club_name: "Almeerse HC",
        home_team_is_current: true,
        home_team_name: "JD1",
        id: "match-apr-1",
        is_cancelled: false,
        is_home_match: true,
        is_selected_team: true,
        location: {
          address: {
            street: "Tuinkruidepad",
            house_number: "4",
            house_number_extension: null,
            zip_code: "1312JN",
            city: "Almere",
          },
          location_quarters: null,
          name: "Sportpark Klein Brandt",
          phones: ["(+31) 36 555 0112"],
          web_pages: ["www.sportpark-klein-brandt.nl"],
        },
        time: "10:00",
      },
    },
    {
      data: {
        arrival_time: "13:00",
        away_team_club_logo_url: "assets/logos/logo-4.jpg",
        away_team_club_name: "HC Enschede",
        away_team_is_current: false,
        away_team_name: "MD1",
        category: "Juniors",
        category_code: "MD1",
        club_remarks: null,
        code: "12356",
        date: "12-04-2026",
        extra_remarks: null,
        field: "Field 2",
        gender: "female",
        home_team_club_logo_url: "assets/logos/logo-4.jpg",
        home_team_club_name: "Almeerse HC",
        home_team_is_current: true,
        home_team_name: "MD1",
        id: "match-apr-2",
        is_cancelled: false,
        is_home_match: false,
        is_selected_team: true,
        location: {
          address: {
            street: "Jan Tinbergenstraat",
            house_number: "10",
            house_number_extension: null,
            zip_code: "7500AB",
            city: "Enschede",
          },
          location_quarters: null,
          name: "Enschede Sports Complex",
          phones: ["(+31) 53 555 0113"],
          web_pages: ["www.enschede-sports.nl"],
        },
        time: "14:00",
      },
    },
    {
      data: {
        arrival_time: "10:30",
        away_team_club_logo_url: "assets/logos/logo-1.jpg",
        away_team_club_name: "HC Dordrecht",
        away_team_is_current: false,
        away_team_name: "AD2",
        category: "Adults",
        category_code: "AD2",
        club_remarks: "Regular season continuation",
        code: "12357",
        date: "12-04-2026",
        extra_remarks: null,
        field: "Field 3",
        gender: "male",
        home_team_club_logo_url: "assets/logos/logo-4.jpg",
        home_team_club_name: "Almeerse HC",
        home_team_is_current: true,
        home_team_name: "AD2",
        id: "match-apr-3",
        is_cancelled: false,
        is_home_match: true,
        is_selected_team: false,
        location: {
          address: {
            street: "Tuinkruidepad",
            house_number: "4",
            house_number_extension: null,
            zip_code: "1312JN",
            city: "Almere",
          },
          location_quarters: null,
          name: "Sportpark Klein Brandt",
          phones: ["(+31) 36 555 0114"],
          web_pages: ["www.sportpark-klein-brandt.nl"],
        },
        time: "11:30",
      },
    },
  ],
  matches_may_2026: [
    {
      data: {
        arrival_time: "08:00",
        away_team_club_logo_url: "assets/logos/logo-2.jpg",
        away_team_club_name: "HC Maastricht",
        away_team_is_current: false,
        away_team_name: "JD1",
        category: "Juniors",
        category_code: "JD1",
        club_remarks: "Pre-summer tournament preparation",
        code: "12358",
        date: "10-05-2026",
        extra_remarks: null,
        field: "Field 1",
        gender: "male",
        home_team_club_logo_url: "assets/logos/logo-4.jpg",
        home_team_club_name: "Almeerse HC",
        home_team_is_current: true,
        home_team_name: "JD1",
        id: "match-may-1",
        is_cancelled: false,
        is_home_match: false,
        is_selected_team: true,
        location: {
          address: {
            street: "Maasboulevard",
            house_number: "200",
            house_number_extension: null,
            zip_code: "6200AD",
            city: "Maastricht",
          },
          location_quarters: null,
          name: "Maastricht Sports Center",
          phones: ["(+31) 43 555 0115"],
          web_pages: ["www.maastricht-sports.nl"],
        },
        time: "09:00",
      },
    },
    {
      data: {
        arrival_time: "12:00",
        away_team_club_logo_url: "assets/logos/logo-3.avif",
        away_team_club_name: "HC Nijmegen",
        away_team_is_current: false,
        away_team_name: "MD1",
        category: "Juniors",
        category_code: "MD1",
        club_remarks: null,
        code: "12359",
        date: "10-05-2026",
        extra_remarks: null,
        field: "Field 2",
        gender: "female",
        home_team_club_logo_url: "assets/logos/logo-4.jpg",
        home_team_club_name: "Almeerse HC",
        home_team_is_current: true,
        home_team_name: "MD1",
        id: "match-may-2",
        is_cancelled: false,
        is_home_match: true,
        is_selected_team: true,
        location: {
          address: {
            street: "Tuinkruidepad",
            house_number: "4",
            house_number_extension: null,
            zip_code: "1312JN",
            city: "Almere",
          },
          location_quarters: null,
          name: "Sportpark Klein Brandt",
          phones: ["(+31) 36 555 0116"],
          web_pages: ["www.sportpark-klein-brandt.nl"],
        },
        time: "13:30",
      },
    },
  ],
};

// Mock API functions
export const api = {
  collections: {
    getCollection: ({ collectionName }) => {
      return Promise.resolve(mockCollectionData[collectionName] || []);
    },
  },
};
